#!/usr/bin/env bash
#configure Nginx server to redirect to another page
#!/usr/bin/env bash
# automate installation and set up of nginx web server, redirection
# and custom error messages

sudo apt-get update -y

sudo apt-get install nginx -y

sudo ufw allow 'Nginx HTTP'

sudo chown -R $USER:$USER /var/www

sudo chmod -R 755 /var/www

redirect_str="server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.google.com;\n\t}\n\n\tlocation \/ {\n\t\ttry_files \$uri \$uri\/ =404;\n\t}\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\tinternal;\n\t}"

sudo sed -i "s/server_name _;/$redirect_str/" /etc/nginx/sites-enabled/default

# Create the custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

sudo service nginx restart
