#!/bin/env bash
# Install Nginx if it is not already installed

sudo apt-get update -y

sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'

sudo chown -R $USER:$USER /var/www

sudo chmod -R 755 /var/www

echo "Hello World!" | sudo tee /var/www/html/index.html

HEADER_NAME="X-Served-By"

# Get the hostname of the server
# HOSTNAME=$(hostname)

if ! grep -q "add_header X-Served-By" /etc/nginx/sites-available/default; then
    sudo sed -i '/^\s*server\s*{/a \\n    add_header X-Served-By $hostname;\n' /etc/nginx/sites-available/default
fi

sudo /etc/init.d/nginx restart
