#!/bin/env bash
# Install Nginx if it is not already installed

sudo apt-get update -y

sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'

sudo chown -R $USER:$USER /var/www

sudo chmod -R 755 /var/www

echo "Hello World!" | sudo tee /var/www/html/index.html

replace_str="location \/ {\n\tadd_header X-Served-By $hostname;\n"

sudo sed -i "s/location \//$replace_str/" /etc/nginx/sites-available/default

sudo /etc/init.d/nginx restart
