#!/bin/env bash
# Install Nginx if it is not already installed

ADD_HEADER="\\\tadd_header X-Served-By $HOSTNAME;"

sudo apt-get update -y

sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'

sudo chown -R $USER:$USER /var/www

sudo chmod -R 755 /var/www

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i "27i $ADD_HEADER" /etc/nginx/sites-available/default

sudo service nginx restart
