#!/usr/bin/env bash
# Installs and configure HAproxy on your lb-01 server.

sudo apt-get update -y

sudo apt-get install haproxy -y

cfg=\
"
frontend ifingers-frontend
	 bind *:80
	 mode http
	 default_backend ifingers-backend
backend ifingers-backend
	mode http
	balance roundrobin
	server 266471-web-01 100.24.244.124:80 check
	server 266471-web-02 18.210.33.175:80 check
"
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

echo "$cfg" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
