#!/usr/bin/env bash
# Configure server with: HAproxy version 1.5 or greater
# Distributes request using roundrobin; sends traffic to servers: web-01 and web-02

# CFG="\\\nlisten appname 0.0.0.0:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 266471-web-01 100.24.244.124 check\n\tserver 266471-web-02 18.210.33.175 check\n"

sudo apt-get update
sudo apt-get install -y haproxy

# Make sure HAproxy can be managed via an init script
sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy

# Backup original config file before attempt modifications
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

echo "
frontend frontend_proxying
	 bind *:80
	 default_backend web_servers

backend web_servers
	balance roundrobin
	server 266471-web-01 100.24.244.124 check
	server 266471-web-02 18.210.33.175 check
" | sudo tee /etc/haproxy/haproxy.cfg > dev/null
# Configure to include roundrobin and two servers
# sudo sed -i "\$a $CFG" /etc/haproxy/haproxy.cfg

sudo service haproxy start
