#!/usr/bin/env bash
# Loops from 1 to 10, display, bad luck, good luck and best school
i="0"
while [ $i -lt 10 ]
do

    if [ $i = 3 ]; then
	echo "bad luck"
    elif [ $i = 7 ]; then
	echo "good luck"
    else
	
    fi
    echo "Best School"    
    i=$(( i+1 ))
done
