#!/usr/bin/env bash
# displays the content of the file /etc/passwd
while IFS=':' read -r user passwd uid gid info home cmdshell; do
    echo "The user $user is part of the $gid gang, lives in $home and rides\
 $cmdshell. $uid's place is protected by the passcode $passwd, \
more info about the user here: $info"
    done < /etc/passwd
