#!/usr/bin/env bash
#displays the time for 12 hours and 59 minutes
hrs="0"
while [ $hrs -le 12 ]; do
    mins="1"
    echo "Hours: ${hrs}"
    while [ $mins -le 59 ]; do
	echo "$mins"
	mins=$(( mins+1 ))
    done
    hrs=$(( hrs+1 ))
done
