#!/usr/bin/env bash
#Displays content of the current directory in a list format
for file in *
do
    if [[ ! "$file" == .* && "$file" == *-* ]]
    then
	name=$(echo "$file" | cut -d '-' -f 2-)
	echo "$name"
    fi
done
