#!/usr/bin/env bash
# Fix container so that Nginx is running as the nginx user.

NGINX_CONF="/etc/nginx/nginx.conf"

sudo sed -i 's/#user www-data/user nginx/' $NGINX_CONF
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
